workflows:
  ios-workflow:
    name: iOS Build and Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Adicione suas variáveis de ambiente no Codemagic UI:
        # - CERTIFICATE_PRIVATE_KEY (base64 do certificado .p12)
        # - APP_STORE_CONNECT_ISSUER_ID
        # - APP_STORE_CONNECT_KEY_IDENTIFIER
        # - APP_STORE_CONNECT_PRIVATE_KEY (base64)
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - giovanni.manzatto@fraktalsoftwares.com.br
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
