workflows:
  ios-workflow:
    name: iOS Build and Deploy to TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        # Configure estas variáveis no Codemagic UI (Team settings > Environment variables):
        # - APP_STORE_CONNECT_ISSUER_ID (obrigatório)
        # - APP_STORE_CONNECT_KEY_IDENTIFIER (obrigatório)
        # - APP_STORE_CONNECT_PRIVATE_KEY (obrigatório - conteúdo do arquivo .p8)
        # - CERTIFICATE_PRIVATE_KEY (obrigatório - certificado .p12 em base64)
        # - CERTIFICATE_PASSWORD (obrigatório - senha do certificado .p12)
        # - PROVISIONING_PROFILE_SPECIFIER (opcional - nome do provisioning profile)
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - giovanni.manzatto@fraktalsoftwares.com.br
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        # Usa as variáveis de ambiente configuradas acima
        submit_to_testflight: true
        beta_groups:
          # Adicione os nomes dos grupos de teste do TestFlight aqui (opcional)
          # - "Internal Testers"
          # - "External Testers"
